[project]
name = "xxt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.0",
    "selenium>=4.33.0",
    "tqdm>=4.67.1",
    "webdriver-manager>=4.0.2",
]
